repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        exclude: ^\.github/
    -   id: check-toml
        exclude: ^\.github/
    -   id: check-yaml
        args:
        -   --unsafe
        exclude: ^\.github/
    -   id: end-of-file-fixer
        exclude: ^\.github/
    -   id: trailing-whitespace
        exclude: ^\.github/
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
    -   id: ruff
        args:
        - --fix
        exclude: ^\.github/
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^\.github/
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        exclude: ^\.github/
